version: "3.8"
services:
  app:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/app
      - public:/app/public
      - tmp:/app/tmp
    ports:
      - "3000:3000"
  proxy:
    build:
      context: nginx
    volumes:
      - public:/app/public
      - tmp:/app/tmp
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  public:
  tmp:
